---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: assign
  labels:
    app: assign
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assign
  template:
    metadata:
      labels:
        app: assign
    spec:
      containers:
        - name: assign
          image: username/assign:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: driving
  labels:
    app: driving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driving
  template:
    metadata:
      labels:
        app: driving
    spec:
      containers:
        - name: driving
          image: username/driving:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: assign
  labels:
    app: assign
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: assign


---


apiVersion: v1
kind: Service
metadata:
  name: driving
  labels:
    app: driving
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: driving

